prompt:
  sora-type:
    T: ${PROMPT_T}
    F: ${PROMPT_F}


spring:
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${OPEN_AI_MODEL}
        project-id: ${OPEN_AI_PROJECT}

logging:
  level:
    magicofconch.sorawebflux.review.service.SoraService: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXP}
    refresh: ${JWT_REFRESH_EXP}

sora:
  srv:
    url: ${SORA_SRV_URL}

dify:
  api-key:
    F: ${DIFY_F_API_KEY}
    T: ${DIFY_T_API_KEY}

### Actuator & Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name:sora-webflux}
